//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen_2_AppServWEB.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class FotoInfraccion
    {
        public int idFoto { get; set; }
        public string NombreFoto { get; set; }
        public int idInfraccion { get; set; }
        [JsonIgnore]
        public virtual Infraccion Infraccion { get; set; }
    }
}
