//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen_2_AppServWEB.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Infraccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Infraccion()
        {
            this.FotoInfraccions = new HashSet<FotoInfraccion>();
        }
    
        public int idFotoMulta { get; set; }
        public string PlacaVehiculo { get; set; }
        public System.DateTime FechaInfraccion { get; set; }
        public string TipoInfraccion { get; set; }
        [JsonIgnore]

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FotoInfraccion> FotoInfraccions { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
